### ISSUE TITLE
[Linux] Build Error on Ubuntu 18.04 & VST3 SDK 3.6.9

### ISSUE THREAD

**Issue by c0m0r1** [igorski/regrader#8] opened 2020-05-12 17:35 UTC
Hello, I have compile error while using Ubuntu 18.04 & VST3 SDK 3.6.9
while doing cmake on regrader directory, following error shows up
```
CMake Error at /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:25 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:validator>

  No target "validator"
Call Stack (most recent call first):
  /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:129 (smtg_run_vst_validator)
  CMakeLists.txt:186 (smtg_add_vst3plugin)


CMake Error at /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:19 (add_dependencies):
  The dependency target "validator" of target "regrader" does not exist.
Call Stack (most recent call first):
  /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:129 (smtg_run_vst_validator)
  CMakeLists.txt:186 (smtg_add_vst3plugin)


CMake Error at /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:25 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:validator>

  No target "validator"
Call Stack (most recent call first):
  /home/kdo6/Desktop/VST_SDK/VST3_SDK/cmake/modules/AddVST3Library.cmake:129 (smtg_run_vst_validator)
  CMakeLists.txt:186 (smtg_add_vst3plugin)
```
However Makefile generated successely. But when I trying to build plugin and test with validator, It shows this error.

```kdo6@ubuntu:~/Desktop/regrader/build$ /home/kdo6/Desktop/VST_SDK/VST3_SDK/build/bin/validator VST3/regrader.vst3
* Loading module...

	/home/kdo6/Desktop/regrader/build/VST3/regrader.vst3

Invalid Module!
dlopen failed.
/home/kdo6/Desktop/regrader/build/VST3/regrader.vst3/Contents/x86_64-linux/regrader.so: undefined symbol: _ZTIN3Gtk11DrawingAreaE
```
Seems somethings went wrong while compling/linking time. How can i solve this?

**Comment by igorski** [comment] 2020-05-15 09:26
Hi, I am upgrading the project to use the latest Steinberg SDK 3.6.14 and hope to tackle the Linux issues as well. Can you checkout branch 3614 and verify whether this solves the issue for you?

**Comment by igorski** [comment] 2020-08-27 16:26
Hi @c0m0r1,

I have been investing some time in the Linux build. Can you verify whether the contents of branch [370](https://github.com/igorski/regrader/pull/10) resolves the linking issue you experienced?

**Comment by igorski** [comment] 2020-08-28 08:30
Confirmed to be a duplicate of https://github.com/igorski/regrader/issues/7

**Closed as completed by igorski** 2020-08-28 08:30 UTC
Labels: duplicate, Linux
